package com.Zeal.Shiyulin.modules.login.pojo;

public class UserPower {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_power.UserId
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_power.IsGag
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Integer isgag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_power.IsVip
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Integer isvip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_power.VisitLevel
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Integer visitlevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_power.UserId
     *
     * @return the value of user_power.UserId
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_power.UserId
     *
     * @param userid the value for user_power.UserId
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_power.IsGag
     *
     * @return the value of user_power.IsGag
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Integer getIsgag() {
        return isgag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_power.IsGag
     *
     * @param isgag the value for user_power.IsGag
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setIsgag(Integer isgag) {
        this.isgag = isgag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_power.IsVip
     *
     * @return the value of user_power.IsVip
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Integer getIsvip() {
        return isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_power.IsVip
     *
     * @param isvip the value for user_power.IsVip
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setIsvip(Integer isvip) {
        this.isvip = isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_power.VisitLevel
     *
     * @return the value of user_power.VisitLevel
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Integer getVisitlevel() {
        return visitlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_power.VisitLevel
     *
     * @param visitlevel the value for user_power.VisitLevel
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setVisitlevel(Integer visitlevel) {
        this.visitlevel = visitlevel;
    }
}