package com.Zeal.Shiyulin.modules.login.pojo;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.username
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.roleid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.userid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.username
     *
     * @return the value of user_login.username
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.username
     *
     * @param username the value for user_login.username
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password
     *
     * @return the value of user_login.password
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password
     *
     * @param password the value for user_login.password
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.roleid
     *
     * @return the value of user_login.roleid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.roleid
     *
     * @param roleid the value for user_login.roleid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.userid
     *
     * @return the value of user_login.userid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.userid
     *
     * @param userid the value for user_login.userid
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}