package com.Zeal.Shiyulin.modules.login.pojo;

public class ZdRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_role.id
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_role.name
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_role.id
     *
     * @return the value of zd_role.id
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_role.id
     *
     * @param id the value for zd_role.id
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_role.name
     *
     * @return the value of zd_role.name
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_role.name
     *
     * @param name the value for zd_role.name
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}