package com.Zeal.Shiyulin.modules.login.mapper;

import com.Zeal.Shiyulin.modules.login.pojo.UserPower;
import com.Zeal.Shiyulin.modules.login.pojo.UserPowerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int countByExample(UserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int deleteByExample(UserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int insert(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int insertSelective(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    List<UserPower> selectByExample(UserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    UserPower selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPower record, @Param("example") UserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByExample(@Param("record") UserPower record, @Param("example") UserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByPrimaryKeySelective(UserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_power
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByPrimaryKey(UserPower record);
}