package com.Zeal.Shiyulin.modules.login.mapper;

import com.Zeal.Shiyulin.modules.login.pojo.ZdLevel;
import com.Zeal.Shiyulin.modules.login.pojo.ZdLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZdLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int countByExample(ZdLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int deleteByExample(ZdLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int insert(ZdLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int insertSelective(ZdLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    List<ZdLevel> selectByExample(ZdLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    ZdLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ZdLevel record, @Param("example") ZdLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByExample(@Param("record") ZdLevel record, @Param("example") ZdLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByPrimaryKeySelective(ZdLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_level
     *
     * @mbggenerated Mon Oct 03 21:52:04 CST 2016
     */
    int updateByPrimaryKey(ZdLevel record);
}